version: '2'
services:
    mariadb:
      image: docker.io/bitnami/mariadb:10.6
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_USER=bn_joomla
        - MARIADB_DATABASE=bitnami_joomla
      volumes:
        - 'mariadb_data:/bitnami/mariadb'
    joomla:
      image: docker.io/bitnami/joomla:4
      ports:
        - '80:8080'
        - '443:8443'
      environment:
        - JOOMLA_DATABASE_HOST=mariadb
        - JOOMLA_DATABASE_PORT_NUMBER=3306
        - JOOMLA_DATABASE_USER=bn_joomla
        - JOOMLA_DATABASE_NAME=bitnami_joomla
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
      volumes:
        - 'joomla_data:/bitnami/joomla'
      depends_on:
        - mariadb

# Сервис сбора метрик сервера
    node-exporter:
        image: prom/node-exporter
        restart: always
        ports:
            - 9100:9100
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
# Сервис метрик из Docker контейнеров
    cadvisor-exporter:
        container_name: "cadvisor-exporter"
        image: gcr.io/cadvisor/cadvisor
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        restart: always
#Сервис сбора метрик MySQL
    mysql-exporter:
        image: prom/mysqld-exporter
        container_name: mysql-exporter
        restart: always
        environment:
        - DATA_SOURCE_NAME=${MYSQL_USER_EXPORTER}:${MYSQL_PASSWORD_EXPORTER}@(mysql:3306)/
        ports:
            - 9104:9104
volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local